Controllers/UserListingController.cs
using CMSClientApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace CMSClientApp.Controllers
{
    public class UserListingController : Controller
    {
        public static string baseUrl = "https://localhost:44385/api/users/";
        public async Task<IActionResult> Index()
        {
            var users = await GetAllUser();
            return View(users);
        }
        [HttpGet]
        public async Task<List<Users>> GetAllUser()
        {
            //use access token to call api
            var accessToken = HttpContext.Session.GetString("JWTToken");
            var url = baseUrl;
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

            string jsonstr = await client.GetStringAsync(url);

            var res = JsonConvert.DeserializeObject<List<Users>>(jsonstr).ToList();

            return res;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CMSClientApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CMSClientApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (Context.User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a>Hello @User.Identity.Name</a>
                            </li>
                            <li>
                                <a asp-controller="Home" asp-action="Logoff">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ml-auto">
                                <a class="nav-link text-dark" asp-controller="home" asp-action="register">
                                    Register
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="GoogleLogin">Login With Google</a>
                            </li>
                        }

                        @*@if (signInManager.IsSignedIn(User))
                            {
                                <li class="nav-item ml-auto">
                                    <form method="post" asp-controller="account" asp-action="logout">
                                        <button type="submit" style="width:auto"
                                                class="nav-link btn btn-link py-0">
                                            Logout @User.Identity.Name
                                        </button>
                                    </form>
                                </li>
                            }

                            else
                            {

                                <li class="nav-item ml-auto">
                                    <a class="nav-link text-dark" asp-controller="account" asp-action="register">
                                        Register
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="account" asp-action="login">
                                        Login
                                    </a>
                                </li>
                            }*@

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CMSClientApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CMSClientApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CMSClientApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserListing" asp-action="Index">Users</a>
                        </li>

                        @if (Context.User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a>Hello @User.Identity.Name</a>
                            </li>
                            <li>
                                <a asp-controller="Home" asp-action="Logoff">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ml-auto">
                                <a class="nav-link text-dark" asp-controller="home" asp-action="register">
                                    Register
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="GoogleLogin" asp-action="Index">Login With Google</a>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CMSClientApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>